spring:
  application:
    name: driver-load
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/driver_load
    username: postgres
    password: pass
  flyway:
    url: jdbc:postgresql://localhost:5432/driver_load
    user: postgres
    password: pass

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG

jwt:
  secret:
    key: 34e7f550e2715c958372db43db8f68c0ea686807bf7eab4f22f2ee673df0f929

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html